theme: jekyll-theme-minimal
title: Dili's AI Playground
description: A blog about fundamental data science and Agentic AI applications

collections:
  projects:
    output: true
  research:
    output: true